Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [9]:
from sklearn.datasets import load_iris
import numpy as np
df = load_iris()

#Extract feature matrix as NumPy array
print('--- Extract feature matrix as NumPy array ---')
feature_arr = df.data
#printing only top 5 rows for space complexity
print(feature_arr[:5])

#Compute: Mean, Median, Standard deviation, Variance (for each feature)
mean = np.mean(feature_arr, axis = 0)
median = np.median(feature_arr, axis = 0)
std_dev = np.std(feature_arr, axis = 0)
variance = np.var(feature_arr, axis = 0)

print('\n--- Compute: Mean, Median, Standard deviation, Variance (for each feature) ---')
print(f"| {'--------------------':<20} | {'----------':<10} | {'----------':<10} | {'----------':<10} | {'----------':<10} |") 
print(f"| {'Feature Name':<20} | {'Mean':<10} | {'Median':<10} | {'Std.Dev':<10} | {'Variance':<10} |")
print(f"| {'--------------------':<20} | {'----------':<10} | {'----------':<10} | {'----------':<10} | {'----------':<10} |")
for index, name in enumerate(df.feature_names):
    print(f'| {name:<20} | {mean[index]:10.6f} | {median[index]:10.6f} | {std_dev[index]:10.6f} | {variance[index]:10.6f} |')
print(f"| {'--------------------':<20} | {'----------':<10} | {'----------':<10} | {'----------':<10} | {'----------':<10} |")

print('\n--- 3. Identify: Which feature has highest variability and why it matters in ML ---')
index = np.argmax(variance)
print(f'{df.feature_names[index]} has the highest variance : {variance[index]:1.6f}')
#To Do
print('To Do : Why highest variablity matters in ML : \n'  
     '         high variance means lot of information and gives the predictive power \n' \
     '         will help in classification. \n'\
     '         Low variance can be removed from feature because all values almost same. add no value to ML')

print('\n---  Convert any one feature into shape (n,1) and explain why ML models expect this format --')
petal_len_arr = feature_arr[:, 2].reshape(-1, 1)
#printing only top 5 rows for space complexity
print(petal_len_arr[:5])
#To Do
print('To Do : Why ML models expects feature in (n,1) or (-1,1) shape : \n'\
    '       ML model always expects data like table (2D)')

--- Extract feature matrix as NumPy array ---
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

--- Compute: Mean, Median, Standard deviation, Variance (for each feature) ---
| -------------------- | ---------- | ---------- | ---------- | ---------- |
| Feature Name         | Mean       | Median     | Std.Dev    | Variance   |
| -------------------- | ---------- | ---------- | ---------- | ---------- |
| sepal length (cm)    |   5.843333 |   5.800000 |   0.825301 |   0.681122 |
| sepal width (cm)     |   3.057333 |   3.000000 |   0.434411 |   0.188713 |
| petal length (cm)    |   3.758000 |   4.350000 |   1.759404 |   3.095503 |
| petal width (cm)     |   1.199333 |   1.300000 |   0.759693 |   0.577133 |
| -------------------- | ---------- | ---------- | ---------- | ---------- |

--- 3. Identify: Which feature has highest variability and why it matters in ML ---
petal length (cm) has the highest variance : 3.095503
To Do : Why highest var

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [12]:
import seaborn as sns

df = sns.load_dataset('iris')
print('--- Extract: First 100 samples Only last 2 features ---')
df.iloc[:100, 2:4]
print(df.iloc[:100, 2:4])

print('\n--- 2. Use boolean masking: Select samples where petal length is greater than dataset mean ---')
df.loc[df['petal_length'] > df['petal_length'].mean(), :]
print(df.loc[df['petal_length'] > df['petal_length'].mean(), :])

print('\n--- Count selected samples ---')
print(df.loc[df['petal_length'] > df['petal_length'].mean(), :]['petal_length'].count())

#To Do
print('\nTo Do : Explain how this relates to feature-based filtering in ML : \n'
     '       Filter Method Selection: This is a filter-based approach, which selects data points or features independently of the final machine learning algorithm. \n'
     '       Removing Noise/Irrelevance: By focusing on samples with high petal lengths, you may be focusing on features that are more informative for distinguishing between Versicolor and Virginica, thus removing the "noise" introduced by the shorter Setosa samples if that class is not the focus. \n'
     '       Dimensionality Reduction: This technique helps in reducing the dimensionality of the data by retaining only relevant subset data points, which simplifies the modeling process. \n'
     '       Improving Interpretability: Selecting samples based on specific criteria makes the model easier to interpret (e.g., "If Petal Length > 3.76, classify as Virginica or Versicolor").')

--- Extract: First 100 samples Only last 2 features ---
    petal_length  petal_width
0            1.4          0.2
1            1.4          0.2
2            1.3          0.2
3            1.5          0.2
4            1.4          0.2
..           ...          ...
95           4.2          1.2
96           4.2          1.3
97           4.3          1.3
98           3.0          1.1
99           4.1          1.3

[100 rows x 2 columns]

--- 2. Use boolean masking: Select samples where petal length is greater than dataset mean ---
     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [116]:
from sklearn.datasets import load_iris

df = load_iris()
feature_iris = df.data
mean = np.mean(feature_iris, axis = 0)
std_dev = np.std(feature_iris, axis = 0)

feature_iris_copy = (feature_iris - mean) / std_dev
print('--- Apply standardization ---')
print('Top 5 rows after applying standardization')
print(feature_iris_copy[:5])

print('\n--- Verify: Mean ≈ 0, Std ≈ one ---')
print(f"Mean after Standardization: {np.mean(feature_iris_copy, axis = 0)}")
print(f"Standard deviation after Standardization : {np.std(feature_iris_copy, axis = 0)}")

--- Apply standardization ---
Top 5 rows after applying standardization
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]

--- Verify: Mean ≈ 0, Std ≈ one ---
Mean after Standardization: [-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
Standard deviation after Standardization : [1. 1. 1. 1.]


Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [118]:
import seaborn as sns

df = sns.load_dataset('titanic')
print('--- Display: head(), tail() info(), describe() ---')
print('Head')
print(df.head())
print('Tail')
print(df.tail())
print('Info')
print(df.info())
print('Describe')
print(df.describe())

print('\n--- Identify: Missing values per column Numerical vs categorical features ---')
print(df.isnull().sum())

#To Do
print('\nTo Do : Explain: Why identifying feature types is important before modeling')

--- Display: head(), tail() info(), describe() ---
Head
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
Tail
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887 

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [148]:
import seaborn as sns

df = sns.load_dataset('titanic').copy()
df.head()
print('--- Filter: Female passengers in 1st class ---')
df_filtered = df[(df['sex'] == 'female') & (df['pclass'] == 1)]
print(df_filtered.iloc[:5, :9])

survival_rate_filtered = df_filtered['survived'].sum() * 100 / df_filtered['survived'].count()
total_survival_rate = df['survived'].sum() * 100 / df['survived'].count()

print(f"\nSurvival rate of women in first class : {survival_rate_filtered:<2.2f}% ")
print(f"Overall survival rate : {total_survival_rate:<2.2f}%")

#To do
print('\nTo Do : Interpret: What insight can be used in ML feature engineering')

--- Filter: Female passengers in 1st class ---
    survived  pclass     sex   age  sibsp  parch      fare embarked  class
1          1       1  female  38.0      1      0   71.2833        C  First
3          1       1  female  35.0      1      0   53.1000        S  First
11         1       1  female  58.0      0      0   26.5500        S  First
31         1       1  female   NaN      1      0  146.5208        C  First
52         1       1  female  49.0      1      0   76.7292        C  First

Survival rate of women in first class : 96.81% 
Overall survival rate : 38.38%

To Do : Interpret: What insight can be used in ML feature engineering


Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [180]:
import seaborn as sns

df = sns.load_dataset('titanic')
print('--- No.of missing value before fillna ---')
print(f"Age : {df['age'].isnull().sum()}")
print(f"Embarked : {df['embarked'].isnull().sum()}")

df.fillna({'age': df['age'].median(),
           'embarked' : df['embarked'].mode()[0]}, inplace = True)

print('\n--- No.of missing value after fillna ---')
print(f"Age : {df['age'].isnull().sum()}")
print(f"Embarked : {df['embarked'].isnull().sum()}")
df.drop(columns='deck', inplace = True)
print('\n--- Dataframe head after removing deck column ---')
print(df.head())
#To Do
print('\nTo Do : Explain: Why different strategies are used for different columns')




--- No.of missing value before fillna ---
Age : 177
Embarked : 2

--- No.of missing value after fillna ---
Age : 0
Embarked : 0

--- Dataframe head after removing deck column ---
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male  embark_town alive  alone  
0    man        True  Southampton    no  False  
1  woman       False    Cherbourg   yes  False  
2  woman       False  Southampton   yes   True  
3  woman       False  Southampton   yes  False  
4    man        True  Southampton    no   True  

To Do : Explain: Why different strategies are used for different colu

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [195]:
import seaborn as sns

df = sns.load_dataset('titanic')
df['family_size'] = df['sibsp'] + df['parch'] + 1
df['is_alone'] = df['family_size'] == 1
print(f"{df.groupby('is_alone')['survived'].mean() * 100} ")

#To Do
print('\nTo Do : Explain: Why engineered features improve ML models')


is_alone
False    50.564972
True     30.353818
Name: survived, dtype: float64 

To Do : Explain: Why engineered features improve ML models


Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [18]:
import seaborn as sns

df = sns.load_dataset('tips')

print('--- Compute: Average tip by day Total bill by gender ---')
total_bill_by_gender = df.groupby('sex', observed = False)['total_bill'].sum()
print(total_bill_by_gender)
      
print('\n--- Create new feature: tip_percentage ---')
df['tip_percentage'] = df['tip'] * 100 / df['total_bill']
print(df.head())

print('\n--- Identify: Which day has highest tipping behavior ---')
tip_by_day = df.groupby('day', observed = False)['tip'].sum()
print(tip_by_day)

print('\n--- To Do : Explain: How this helps in segmentation models ---')


--- Compute: Average tip by day Total bill by gender ---
sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64

--- Create new feature: tip_percentage ---
   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765

--- Identify: Which day has highest tipping behavior ---
day
Thur    171.83
Fri      51.96
Sat     260.40
Sun     247.39
Name: tip, dtype: float64

--- To Do : Explain: How this helps in segmentation models ---


Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [28]:
import seaborn as sns

df = sns.load_dataset('tips')
df.head()

print('--- Filter: total_bill > 20 AND tip < 3 ---')
df_filtered = df[(df['total_bill'] > 20) & (df['tip'] < 3)]
#print(df[(df['total_bill'] > 20) & (df['tip'] < 3)])

print('\n--- Select only relevant columns ---')
print(df_filtered.iloc[:, :2])

--- Filter: total_bill > 20 AND tip < 3 ---

--- 2. Select only relevant columns ---
     total_bill   tip
21        20.29  2.75
33        20.69  2.45
48        28.55  2.05
57        26.41  1.50
68        20.23  2.01
102       44.30  2.50
113       23.95  2.55
119       24.08  2.92
129       22.82  2.18
131       20.27  2.83
153       24.55  2.00
166       20.76  2.24
187       30.46  2.00
192       28.44  2.56
208       24.27  2.03
210       30.06  2.00
229       22.12  2.88
230       24.01  2.00
237       32.83  1.17
240       27.18  2.00
241       22.67  2.00


Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [42]:
import numpy as np

arr_1 = np.array([[1, 2], [3, 4], [5, 6]])
arr_2 = np.array([[7, 8], [9, 10], [11, 12]])

print('--- vertical stacking ---')
print(np.vstack([arr_1, arr_2]))
print('\n--- horizontal stacking ---')
print(np.hstack([arr_1, arr_2]))

print('\n--- Reshape into (2,6) ---')
print(np.vstack([arr_1, arr_2]).reshape(2, 6))

--- vertical stacking ---
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

--- horizontal stacking ---
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]

--- Reshape into (2,6) ---
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [58]:
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import StandardScaler

df_ori = sns.load_dataset('titanic')
df = df_ori.copy()
df.isna().sum()
df.fillna({'age' : df['age'].mean(),
          'embarked' : df['embarked'].mode()[0],
          'embark_town' : df['embark_town'].mode()[0]}, inplace = True)
df.drop(columns = ['deck', 'survived'], inplace = True)

num_cols = df.select_dtypes(include = ['int64', 'float64']).columns
cat_cols = df.select_dtypes(include = ['object', 'category']).columns

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df.loc[:, num_cols])
df_encoded = pd.get_dummies(df, cat_cols, drop_first = True)
df.to_numpy()

array([[0.8273772438659699, 'male', -0.5924805998028931, ...,
        'Southampton', 'no', False],
       [-1.5661069258891576, 'female', 0.6387890120425208, ...,
        'Cherbourg', 'yes', False],
       [0.8273772438659699, 'female', -0.2846631968415396, ...,
        'Southampton', 'yes', True],
       ...,
       [0.8273772438659699, 'female', 0.0, ..., 'Southampton', 'no',
        False],
       [-1.5661069258891576, 'male', -0.2846631968415396, ...,
        'Cherbourg', 'yes', True],
       [0.8273772438659699, 'male', 0.17706290760049057, ...,
        'Queenstown', 'no', True]], shape=(891, 13), dtype=object)

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [66]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset('iris')
df.drop(columns = 'species', inplace = True)
df.corr()
print('petal_length and	petal_width are highly correlated')
df_reduced = df.drop(columns = 'petal_width')
print(df_reduced.columns.to_list())

petal_length and	petal_width are highly correlated
['sepal_length', 'sepal_width', 'petal_length']


Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [81]:
import seaborn as sns

df = sns.load_dataset('titanic')
df.head()

def age_group(age):
    if age < 18:
        return 'child'
    elif age >= 60:
        return 'senior'
    else:
        return 'adult'

df['age_group'] = df['age'].apply(age_group)
survival_rate = df.groupby('age_group')['survived'].sum()*100/df.groupby('age_group')['survived'].count()
print(survival_rate)
print('age group child has the highest survival rate')

age_group
adult     36.436170
child     53.982301
senior    26.923077
Name: survived, dtype: float64
age group child has the highest survival rate


Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [87]:
import numpy as np

np.random.seed(42)
errors = np.random.normal(loc=0, scale=1.0, size=1000)
mean_val = np.mean(errors)
std_val = np.std(errors)

lower_bound = mean_val - 2 * std_val
upper_bound = mean_val + 2 * std_val
outliers = errors[(errors < lower_bound) | (errors > upper_bound)]
print('Mean : ', mean_val)
print('Std.dev : ', std_val)
print('Outlier range : ', lower_bound, ' : ', upper_bound)
print('No.of outliers found : ', len(outliers))

Mean :  0.01933205582232549
Std.dev :  0.9787262077473543
Outlier range :  -1.938120359672383  :  1.9767844713170342
No.of outliers found :  44


Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [91]:
import seaborn as sns

df = sns.load_dataset('tips')
df['tip_percentage'] = df['tip'] * 100 / df['total_bill']
print(df.groupby(['day', 'time'])['total_bill'].sum())

print('Saturday dinner segment is highest revenue segment')

day   time  
Thur  Lunch     1077.55
      Dinner      18.78
Fri   Lunch       89.92
      Dinner     235.96
Sat   Lunch        0.00
      Dinner    1778.40
Sun   Lunch        0.00
      Dinner    1627.16
Name: total_bill, dtype: float64
Saturday dinner segment is highest revenue segment


C:\Users\Mayilraj\AppData\Local\Temp\ipykernel_25772\213859115.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(['day', 'time'])['total_bill'].sum())
